export const ADD_HISTORY = "ADD_HISTORY";
export const GET_CONTENT = "GET_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";