export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const REMOVE_FROM_HISTORY = "REMOVE_FROM_HISTORY";
export const ADD_CONTENT = "ADD_CONTENT";
export const GET_CONTENT = "GET_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";

// FOR FILTERS
export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";